### ISSUE TITLE
版本0.5.6.0 Blender3.6生成控制器时出错

### ISSUE THREAD

**Issue by MarisaDA-ZE** [958261649/Miku_Miku_Rig#14]
点击读取预设时会出现这个问题，直接点击生成控制器也会出现这个问题,日志在最后
![图片](https://github.com/LaoBro/Miku_Miku_Rig/assets/86925192/5fb54ab4-2094-4ccf-9a7f-7225599aa894)

![图片](https://github.com/LaoBro/Miku_Miku_Rig/assets/86925192/012e6599-b082-4b3b-99ad-fc979d383f3d)

以下是日志信息：
bpy.ops.object.select_all(action='SELECT')
bpy.ops.object.delete(use_global=False)
bpy.data.window_managers["WinMan"].addon_filter = 'User'
Traceback (most recent call last):
  File "D:\Program Files\Blender\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

Traceback (most recent call last):
  File "D:\Program Files\Blender\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

bpy.context.space_data.recent_folders_active = 0
已安装模块 (cats-blender-plugin-development)，从 'D:\\Program Files\\Blender\\plugins\\cats-blender-plugin-development.zip' 到 'C:\\Users\\LocalUser\\AppData\\Roaming\\Blender Foundation\\Blender\\3.6\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_search = ""
bpy.data.window_managers["WinMan"].addon_search = "miku"
bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.recent_folders_active = 2
bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.recent_folders_active = 2
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.rigidbody.object_add(type='ACTIVE')
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.rigidbody.constraint_add(type='GENERIC_SPRING')
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.duplicate()
bpy.ops.object.shape_key_add()
Imported MMD model from "D:\MRS Files\模型文件\MMD模型\胡桃\胡桃\胡桃.pmx"
bpy.ops.mmd_tools.import_model(filepath="D:\\MRS Files\\模型文件\\MMD模型\\胡桃\\胡桃\\胡桃.pmx", files=[{"name":"胡桃.pmx", "name":"胡桃.pmx"}], directory="D:\\MRS Files\\模型文件\\MMD模型\\胡桃\\胡桃\\")
bpy.ops.mmd_tools.convert_materials()
bpy.ops.mmd_tools.clear_temp_materials()
bpy.ops.mmd_tools.clear_uv_morph_view()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.mmd_tools.clean_shape_keys()
bpy.ops.mmd_tools.separate_by_materials()
bpy.ops.mmr.rig_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.object.posemode_toggle()
bpy.ops.pose.select_all(action='DESELECT')
bpy.ops.mmr.qa_start()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_end()
bpy.ops.mmr.rig_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.object.posemode_toggle()
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.object.posemode_toggle()
bpy.ops.pose.select_all(action='DESELECT')
bpy.ops.mmr.qa_start()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_skip()
bpy.ops.mmr.qa_end()
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.pose.select_all(action='DESELECT')
bpy.ops.mmr.qa_start()
bpy.ops.mmr.qa_assign()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 429, in execute
    pose_bone.mmr_bone_type=bone_type
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.ops.mmr.qa_end()
bpy.ops.object.posemode_toggle()
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.outliner.item_activate(deselect_all=True)
bpy.ops.mmr.rig_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.context.scene.mmr_property.rig_preset_name = 'MMD_JP'
bpy.ops.mmr.read_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.context.scene.mmr_property.rig_preset_name = 'VRoid'
bpy.ops.mmr.read_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.context.scene.mmr_property.rig_preset_name = 'MMD_JP'
bpy.ops.mmr.read_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute
    set_bone_type(pose,preset)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type
    bone.mmr_bone_type=''
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mmr.rig_preset(read=False)
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 331, in execute
    rig.RIG2(context)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\rig.py", line 152, in RIG2
    if bone.mmr_bone_type !='None':
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mmr.rig_preset()
Python: Traceback (most recent call last):
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 331, in execute
    rig.RIG2(context)
  File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\rig.py", line 152, in RIG2
    if bone.mmr_bone_type !='None':
AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'

**Comment by MarisaDA-ZE** [comment]
> 点击读取预设时会出现这个问题，直接点击生成控制器也会出现这个问题,日志在最后 ![图片](https://user-images.githubusercontent.com/86925192/266837215-5fb54ab4-2094-4ccf-9a7f-7225599aa894.png)
> 
> ![图片](https://user-images.githubusercontent.com/86925192/266837422-012e6599-b082-4b3b-99ad-fc979d383f3d.png)
> 
> 以下是日志信息： bpy.ops.object.select_all(action='SELECT') bpy.ops.object.delete(use_global=False) bpy.data.window_managers["WinMan"].addon_filter = 'User' Traceback (most recent call last): File "D:\Program Files\Blender\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 369, in enable mod.register() File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-master__init__.py", line 319, in register bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'} ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')
> 
> Traceback (most recent call last): File "D:\Program Files\Blender\blender-3.6.0-windows-x64\3.6\scripts\modules\addon_utils.py", line 369, in enable mod.register() File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-master__init__.py", line 319, in register bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'} ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')
> 
> bpy.context.space_data.recent_folders_active = 0 已安装模块 (cats-blender-plugin-development)，从 'D:\Program Files\Blender\plugins\cats-blender-plugin-development.zip' 到 'C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons' bpy.data.window_managers["WinMan"].addon_search = "" bpy.data.window_managers["WinMan"].addon_search = "miku" bpy.context.space_data.recent_folders_active = 1 bpy.context.space_data.recent_folders_active = 2 bpy.context.space_data.recent_folders_active = 1 bpy.context.space_data.recent_folders_active = 2 bpy.ops.object.editmode_toggle() bpy.ops.object.editmode_toggle() bpy.ops.object.editmode_toggle() bpy.ops.object.editmode_toggle() bpy.ops.rigidbody.object_add(type='ACTIVE') bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.rigidbody.constraint_add(type='GENERIC_SPRING') bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.duplicate() bpy.ops.object.shape_key_add() Imported MMD model from "D:\MRS Files\模型文件\MMD模型\胡桃\胡桃\胡桃.pmx" bpy.ops.mmd_tools.import_model(filepath="D:\MRS Files\模型文件\MMD模型\胡桃\胡桃\胡桃.pmx", files=[{"name":"胡桃.pmx", "name":"胡桃.pmx"}], directory="D:\MRS Files\模型文件\MMD模型\胡桃\胡桃\") bpy.ops.mmd_tools.convert_materials() bpy.ops.mmd_tools.clear_temp_materials() bpy.ops.mmd_tools.clear_uv_morph_view() bpy.ops.object.select_all(action='DESELECT') bpy.ops.object.editmode_toggle() bpy.ops.mesh.select_all(action='SELECT') bpy.ops.object.editmode_toggle() bpy.ops.mmd_tools.clean_shape_keys() bpy.ops.mmd_tools.separate_by_materials() bpy.ops.mmr.rig_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.object.posemode_toggle() bpy.ops.pose.select_all(action='DESELECT') bpy.ops.mmr.qa_start() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_end() bpy.ops.mmr.rig_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.object.posemode_toggle() bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.object.posemode_toggle() bpy.ops.pose.select_all(action='DESELECT') bpy.ops.mmr.qa_start() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_skip() bpy.ops.mmr.qa_end() bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.pose.select_all(action='DESELECT') bpy.ops.mmr.qa_start() bpy.ops.mmr.qa_assign() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 429, in execute pose_bone.mmr_bone_type=bone_type AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.ops.mmr.qa_end() bpy.ops.object.posemode_toggle() bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.outliner.item_activate(deselect_all=True) bpy.ops.mmr.rig_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 330, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.context.scene.mmr_property.rig_preset_name = 'MMD_JP' bpy.ops.mmr.read_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.context.scene.mmr_property.rig_preset_name = 'VRoid' bpy.ops.mmr.read_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.context.scene.mmr_property.rig_preset_name = 'MMD_JP' bpy.ops.mmr.read_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 280, in execute set_bone_type(pose,preset) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 152, in set_bone_type bone.mmr_bone_type='' AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.ops.object.select_all(action='DESELECT') bpy.ops.object.transform_apply(location=True, rotation=True, scale=True) bpy.ops.object.editmode_toggle() bpy.ops.mmr.rig_preset(read=False) Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 331, in execute rig.RIG2(context) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\rig.py", line 152, in RIG2 if bone.mmr_bone_type !='None': AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type' bpy.ops.object.select_all(action='DESELECT') bpy.ops.object.transform_apply(location=True, rotation=True, scale=True) bpy.ops.object.editmode_toggle() bpy.ops.mmr.rig_preset() Python: Traceback (most recent call last): File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 331, in execute rig.RIG2(context) File "C:\Users\LocalUser\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\MikuMikuRig\mmr_operators\rig.py", line 152, in RIG2 if bone.mmr_bone_type !='None': AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'

**Comment by MarisaDA-ZE** [comment]
先说结论，不要自己打包，下载作者打包好的，插件0.5.6.0对应blender3.6是可以使用的，至少我是这样。

![ask](https://github.com/LaoBro/Miku_Miku_Rig/assets/86925192/7ee4b788-f90d-46ad-91a4-1cd2d773f0de)

如果是从这里下载然后自己将MikuMikuRig文件夹打包的或许会出现上面的问题（至少我是这么操作，并出现了问题的），分享下关于我是怎么解决这个问题的：我从作者留下的B站链接我找到了作者在21年制作的使用视频，其中最新的评论里我看到了和我类似的问题，他的blender是3.5的版本（我的是3.6），同样出现了“AttributeError: 'PoseBone' object has no attribute 'mmr_bone_type'”这个提示，他使用0.5.6.0版本的插件会出错，但是使用0.5.5.0则不会，于是我尝试寻找历史版本进行尝试，但是我使用0.5.5.0版本的插件还是会出现这个问题。于是我想是不是我打包的文件出现了问题，我就下载了作者打好的最新版本的插件包，安装后就正常了。
不过，虽然不用自己打包，但是那个3.0rigify补丁还是要下载替换的。
