### ISSUE TITLE
blender 3.1 求支持

### ISSUE THREAD

**Issue by Rikka93** [958261649/Miku_Miku_Rig#8]

**Comment by Kashouryo** [comment]
Issue when generating rig for a VRM model in 3.1
```
Python: Traceback (most recent call last):
  File "C:\Users\Honoka\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MikuMikuRig\mmr_operators\preset.py", line 311, in execute
    rig.RIG2(context)
  File "C:\Users\Honoka\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MikuMikuRig\mmr_operators\rig.py", line 197, in RIG2
    finger_name1=preset_dict['f_index.01.L']
KeyError: 'f_index.01.L'

location: <unknown location>:-1

```

**Comment by Rikka93** [comment]
Same for MMD model

**Comment by 958261649** [comment]
> Same for MMD model

The latest version is ready for blender3.1
